### PR TITLE
[Glimmer2] Use the document service for glimmer

### PR DESCRIPTION
**Pull request by chadhietala**

### CODE REVIEW

**Comment by lukemelia** [comment]
@chadhietala thanks for working on this. It looks like there are a lot of failing tests from this PR.

**Comment by chadhietala** [comment]
@lukemelia Yea sorry forgot to import `getOwner`. Should be good now. Was wondering if you could do a release as well sense this breaks in FastBoot.

**Comment by lukemelia** [comment]
Thanks @chadhietala. Released as 0.5.0. Would love a confirmation that it works in Fastboot for you.

**Comment by miguelcobain** [comment]
Does this line https://github.com/yapplabs/ember-wormhole/blob/master/addon/utils/dom.js#L51
make sense with this one https://github.com/yapplabs/ember-wormhole/blob/master/addon/components/ember-wormhole.js#L41

I'm getting errors because we're basically looking `document` in `document`.
It happens on latest beta 2.10.

**Comment by krisselden** [comment]
This is not glimmer specific this worked before glimmer

**Comment by miguelcobain** [comment]
@krisselden I think I didn't understand what you mean.

The point is that this PR returns `document` on glimmer.
Then the component looks up `document` on that value.

Isn't this a bug?

**Comment by miguelcobain** [comment]
Update: I've downgraded to 0.4.1 and tests now pass in all ember-try scenarios.

**Pull request merged**
