### PR TITLE
Update build and test dependencies. Test with Octane and Classic.

### PR DESCRIPTION
**Pull request by krisselden**
* update ember cli
* migrate to new testing helpers
* migrate from ember-fastboot-addon-tests to ember-cli-fastboot-testing
* test in LTS and with octane and classic defaults

### CODE REVIEW

**Review by lukemelia — CHANGES_REQUESTED** [review]
Thanks @krisselden. All looks good except that you removed the README content.

**Comment by krisselden** [comment]
I also need to figure out the fastboot tests

**Comment by krisselden** [comment]
@lukemelia I fixed the missing readme and I migrated the fastboot tests to ember-cli-fastboot-testing.

I also reduced some test dependence on jquery but I didn't quite remove it, since a lot of tests use the 'contains' selector.

**Comment by lukemelia** [comment]
🎉

**Pull request merged**
