### PR TITLE
Add FastBoot tests

### PR DESCRIPTION
**Pull request by simonihmig**
Adds FastBoot tests. One with `renderInPlace` which is passing, and one normal one which is failing due to #86. #96 will hopefully fix the failing test...

### CODE REVIEW

**Comment by krisselden** [comment]
@simonihmig I merge #96 can you rebase?

**Comment by simonihmig** [comment]
@krisselden did that. Still a failing test, will investigate...

**Comment by krisselden** [comment]
thank you

**Comment by simonihmig** [comment]
Stupid me, was just a copy paste error in tests... 🙄

Passing locally now, Travis will hopefully confirm...

**Comment by simonihmig** [comment]
Travis is good to us! 🎉

**Comment by sandydoo** [comment]
Awesome! Thanks @simonihmig and @krisselden for getting this done!

**Comment by simonihmig** [comment]
No Problem! @krisselden is this good to be merged?

**Pull request merged**
