### PR TITLE
[BUGFIX] If `renderInPlace` is true, destinationElement is ignored

### PR DESCRIPTION
**Pull request by cibernox**
I found this because I had a component that used ember-wormhole internally like this:

```hbs
{{#ember-wormhole renderInPlace=renderInPlace destinationElement=destinationElement}}
  {{yield}}
{{/ember-wormhole}}
```

and it did complain about `destinationElement` being null, when it wasn't necessary.

### CODE REVIEW

**Comment by lukemelia** [comment]
@cibernox Thanks! It looks like there is a test failure as a result.

**Comment by cibernox** [comment]
I'll check it in a moment.

**Comment by cibernox** [comment]
@lukemelia Fixed. As I see it, the failing test was asserting the wrong thing. At least in my mental model I think that `renderInPlace=true` wins over `destinationElement`.

**Comment by lukemelia** [comment]
@cibernox I'm with you on that.

**Comment by cibernox** [comment]
The failures seem unrelated now 🤔

**Comment by cibernox** [comment]
@lukemelia do you want me to track those errors in master?

**Comment by lukemelia** [comment]
@cibernox If you have time, I would be even more appreciative of you than I am everytime I use ember-power-select!

**Comment by cibernox** [comment]
@lukemelia I'll do it tonight. 

Before I start, given that canary is 3.0.0, how do you feel about dropping support for Ember 1.13 and make 2.4 the first supported LTS? This is regardless of fixing CI, just thinking ahead.

**Comment by lukemelia** [comment]
@cibernox I'm open to that.

**Comment by cibernox** [comment]
@lukemelia Rebased & green

**Comment by lukemelia** [comment]
Merged. Thank you, Miguel. Sent you an invite to have commit bit, too.

**Comment by cibernox** [comment]
Thanks! If you could release a new patch version I'll update it in EPS.

**Comment by lukemelia** [comment]
@cibernox Released as 0.5.4

**Pull request merged**
